package com.example.besu

object AckTags {
    // MATRIX HELP GUIDE



    const val HEADER_SHORTCUTS = "header_shortcuts"
    const val MATRIX_ROOT_IDENTITY = "matrix_root_identity"

    const val MACRO_TEMPLATE_INPUT = "macro_template_input"
    const val MATRIX_COMMIT_BUTTON = "matrix_commit_button"
    const val MATRIX_PLAY_BUTTON = "matrix_play_button"



    
    // --- NAVIGATION ---
    const val MODE_TOGGLE_BTN = "MODE_TOGGLE_BTN"

    // --- MATRIX VIEW ---

    const val MATRIX_VIEW = "MATRIX_VIEW"           // The main container box

    // --- SETTINGS ---
    const val UPLOAD_BTN = "UPLOAD_BTN"

    
    // --- DIALOGS ---






    const val MATRIX_CONTEXT_ADD = "MATRIX_CONTEXT_ADD"









    const val AUDIO_PROFILE_SELECT = "AUDIO_PROFILE_SELECT"
    const val AUDIO_SAVE = "AUDIO_SAVE"




    const val QUICK_ACTION_GROUP = "QUICK_ACTION_GROUP"
    const val QUICK_ACTION_GROUP_EDIT = "QUICK_ACTION_GROUP_EDIT"
    const val QUICK_ACTION_SLOT = "QUICK_ACTION_SLOT"
    const val QUICK_ACTION_SAVE = "QUICK_ACTION_SAVE"

    const val EMERGENCY_SLOT = "EMERGENCY_SLOT"
    const val EMERGENCY_SAVE = "EMERGENCY_SAVE"
    const val EMERGENCY_OVERRIDES = "EMERGENCY_OVERRIDES"
    const val EMERGENCY_INFO = "EMERGENCY_INFO"
    const val EMERGENCY_INFO_SAVE = "EMERGENCY_INFO_SAVE"

    const val EMOJI_SLOT = "EMOJI_SLOT"
    const val EMOJI_LIBRARY = "EMOJI_LIBRARY"
    const val EMOJI_RELATED_PANEL = "EMOJI_RELATED_PANEL"

    const val GIF_IMPORT = "GIF_IMPORT"
    const val GIF_IMPORT_COMMIT = "GIF_IMPORT_COMMIT"
    const val GIF_CATEGORY = "GIF_CATEGORY"
    const val GIF_LANDSCAPE_TOGGLE = "GIF_LANDSCAPE_TOGGLE"



    const val HELP_BUTTON = "HELP_BUTTON"

    const val DECK_SELECTOR = "DECK_SELECTOR"
    const val DECK_CREATE_BUTTON = "DECK_CREATE_BUTTON"
    const val DECK_MANAGE_BUTTON = "DECK_MANAGE_BUTTON"
    const val DECK_CREATE_TYPE = "DECK_CREATE_TYPE"
    const val DECK_CREATE_COMMIT = "DECK_CREATE_COMMIT"

    const val PROFILE_SELECTOR = "PROFILE_SELECTOR"

    const val LIVE_LINK = "LIVE_LINK"
    const val CONFIG_BUTTON = "CONFIG_BUTTON"


    const val EDIT_NODE_DIALOG = "EDIT_NODE_DIALOG"
    const val MATRIX_ROW_TARGET = "MATRIX_ROW_TARGET"
    const val MANUAL_INPUT_BTN = "MANUAL_INPUT_BTN"


    const val SETTINGS_WATCH_AUDIO = "SETTINGS_WATCH_AUDIO"
    const val SETTINGS_WATCH_CONFIG = "SETTINGS_WATCH_CONFIG"
    const val SETTINGS_ENV_SENSOR = "SETTINGS_ENV_SENSOR"
    const val SETTINGS_SHORTCUTS = "SETTINGS_SHORTCUTS"
    const val SETTINGS_DATA_PORT = "SETTINGS_DATA_PORT"
    const val SETTINGS_AUDIO_ROUTING = "SETTINGS_AUDIO_ROUTING"
    const val SETTINGS_TERMINAL_LOG = "SETTINGS_TERMINAL_LOG"

    const val TARGETS_VIEW = "TARGETS_VIEW"
    const val GEO_VIEW = "GEO_VIEW"
    const val GEO_MAP_IMPORT = "GEO_MAP_IMPORT"
    const val TERMINAL_VIEW = "TERMINAL_VIEW"

    // NEW: HELP Module support

    // --- SETTINGS HELP TARGETS ---

    // --- TARGET COMPUTER HELP TARGETS ---
    const val TARGET_SLOT = "TARGET_SLOT"
    const val COMPUTER_STATUS_INDICATOR = "COMPUTER_STATUS_INDICATOR"
    const val COMPUTER_GUIDE_ME = "COMPUTER_GUIDE_ME"
    const val COMPUTER_ADD_CATEGORY = "COMPUTER_ADD_CATEGORY"
    const val COMPUTER_TREE_WINDOW_MODE = "COMPUTER_TREE_WINDOW_MODE"
    const val MATRIX_INSERT_COMPUTER_TAG = "MATRIX_INSERT_COMPUTER_TAG"

    // --- MANUAL OVERRIDE // TARGET COMPUTER INTEGRATION ---
    const val MANUAL_TARGET_QUICK_ROW = "MANUAL_TARGET_QUICK_ROW"
    const val MANUAL_TARGET_BROWSE_TOGGLE = "MANUAL_TARGET_BROWSE_TOGGLE"
    const val MANUAL_MEMORY_BANKS_BTN = "MANUAL_MEMORY_BANKS_BTN"
    const val MANUAL_HEADER_TAKEOVER = "MANUAL_HEADER_TAKEOVER"
    const val MANUAL_HEADER_BROWSE_TOGGLE = "MANUAL_HEADER_BROWSE_TOGGLE"

    // --- AUDIO ARCHITECT HELP TARGETS ---
    const val AUDIO_MASTER_GAIN = "AUDIO_MASTER_GAIN"

    const val AUDIO_VOICE_PICKER = "AUDIO_VOICE_PICKER"
    const val AUDIO_PITCH_SPEED = "AUDIO_PITCH_SPEED"
    const val AUDIO_ROBOTIC_OVERLAY = "AUDIO_ROBOTIC_OVERLAY"
    const val AUDIO_BITCRUSH = "AUDIO_BITCRUSH"
    const val AUDIO_PROFILE_MANAGE = "AUDIO_PROFILE_MANAGE"

    // --- VOICE RECORDINGS HELP TARGETS ---
    // Shared VoiceRecordingPanel buttons -- tagged once, so these apply
    // wherever the panel is embedded (Quick Actions slot, Quick-Access key,
    // Matrix node, and MANAGE RECORDINGS' RE-RECORD panel alike).
    const val VOICE_REC_RECORD_BTN = "VOICE_REC_RECORD_BTN"
    const val VOICE_REC_STOP_BTN = "VOICE_REC_STOP_BTN"
    const val VOICE_REC_PLAY_BTN = "VOICE_REC_PLAY_BTN"
    const val VOICE_REC_ACCEPT_BTN = "VOICE_REC_ACCEPT_BTN"
    const val VOICE_REC_DISCARD_BTN = "VOICE_REC_DISCARD_BTN"
    const val VOICE_REC_REMOVE_BTN = "VOICE_REC_REMOVE_BTN"

    // Matrix-only recording controls (DesignSystem.kt's node editor).
    const val VOICE_REC_MATRIX_ATTACH_BTN = "VOICE_REC_MATRIX_ATTACH_BTN"
    const val VOICE_REC_MATRIX_OVERRIDE_FIELD = "VOICE_REC_MATRIX_OVERRIDE_FIELD"
    const val VOICE_REC_MATRIX_REENABLE_BTN = "VOICE_REC_MATRIX_REENABLE_BTN"

    // MANAGE RECORDINGS (SettingsView.kt's launch button, and the tree
    // browser itself).
    const val VOICE_REC_MANAGE_BTN = "VOICE_REC_MANAGE_BTN"
    const val VOICE_REC_MANAGE_TREE = "VOICE_REC_MANAGE_TREE"
    const val VOICE_REC_MANAGE_LEAF = "VOICE_REC_MANAGE_LEAF"
    const val VOICE_REC_MANAGE_OVERLAY_TOGGLE = "VOICE_REC_MANAGE_OVERLAY_TOGGLE"

}
